### ISSUE TITLE
What's the difference between tcn and tcn_new?

### ISSUE THREAD

**Issue by shiningliang** [YuanTingHsieh/TF_TCN#3]
Hi Nice work!
I wan to know the difference between tcn.py and tcn_new.py.
Thanks

**Comment by YuanTingHsieh** [comment]
Hi @shiningliang 
Thanks for the comment!

Actually tcn_new.py is the experimental codes that I am working on,
still trying new things in there.

I have removed it to avoid confusion.
You can take a look at tcn.py again
I have commented it more

Let me know if any questions 
Best
