### ISSUE TITLE
Small issue in tcn.py

### ISSUE THREAD

**Issue by johnlee09** [YuanTingHsieh/TF_TCN#4]
Hi, Yuan Ting,

Thank you very much for the implementation. Very nice code!

There is a small issue in lines 190 and 196 (tcn.py) where TemporalBlock calls attentionBlock. Values for "counters" and "dropout" should be passed to attentionBlock.

**Comment by YuanTingHsieh** [comment]
Hi John,

You are right!
Thanks for pointing out,
I have fixed that in latest commit.
