### ISSUE TITLE
why not in TCN

### ISSUE THREAD

**Issue by kingaza** [YuanTingHsieh/TF_TCN#6]
Hi @YuanTingHsieh ,

I am curious why these are marked with 'not in TCN'
Actually they shall work.
```
        atten: (not in TCN) add self attention block after Conv.
        use_highway: (not in TCN) use highway as residual connection
        gated: (not in TCN) use gated linear unit as activation
```

**Comment by YuanTingHsieh** [comment]
These comments just mean they are not in the original implementation of TCN.
I put them there just for experimenting if they work well or not.
They will work if you turn them on, you are right
